"""Update order model with payment_status and updated_at

Revision ID: 18b6a64bd66c
Revises: 3144588f4d7a
Create Date: 2026-01-10 14:36:03.659798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18b6a64bd66c'
down_revision = '3144588f4d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Handle branding_detail table - convert deadline to DATE
    op.execute('ALTER TABLE branding_detail ALTER COLUMN deadline TYPE DATE USING deadline::date')
    
    # 2. Handle order_item table changes
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('qty',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_order_item_product', 'products', ['product_id'], ['id'])
    
    # 3. Handle orders table changes
    # Add payment_status with default value, then set NOT NULL
    op.execute("ALTER TABLE orders ADD COLUMN payment_status VARCHAR(30) DEFAULT 'unpaid'")
    op.execute("UPDATE orders SET payment_status = 'unpaid' WHERE payment_status IS NULL")
    op.execute("ALTER TABLE orders ALTER COLUMN payment_status SET NOT NULL")
    
    # Add updated_at with default value, then set NOT NULL
    op.execute("ALTER TABLE orders ADD COLUMN updated_at TIMESTAMP DEFAULT now()")
    op.execute("UPDATE orders SET updated_at = COALESCE(created_at, now()) WHERE updated_at IS NULL")
    op.execute("ALTER TABLE orders ALTER COLUMN updated_at SET NOT NULL")
    
    # Other column modifications for orders table
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               nullable=False)
        batch_op.alter_column('mpesa_receipt',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('mpesa_receipt',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('payment_status')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_item_product', type_='foreignkey')
        batch_op.alter_column('qty',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    op.execute('ALTER TABLE branding_detail ALTER COLUMN deadline TYPE VARCHAR(50)')
    
    # ### end Alembic commands ###