"""drop columns

Revision ID: 60e7f3a8cfad
Revises: a619129f634d
Create Date: 2026-01-23 11:57:10.947659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60e7f3a8cfad'
down_revision = 'a619129f634d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('otp_attempts', sa.Integer(), nullable=True))
        batch_op.drop_constraint('admin_users_reset_token_key', type_='unique')
        batch_op.drop_constraint('admin_users_verification_token_key', type_='unique')
        batch_op.drop_column('reset_token_expires')
        batch_op.drop_column('full_name')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('verification_token_expires')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('verification_token_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('admin_users_verification_token_key', ['verification_token'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint('admin_users_reset_token_key', ['reset_token'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('otp_attempts')
        batch_op.drop_column('otp_expires')
        batch_op.drop_column('otp_code')

    # ### end Alembic commands ###
